### ISSUE TITLE
No way of including previously defined bundles in YAML files

### ISSUE THREAD

**Issue by bradwright** [miracle2k/webassets#118]
I would expect this to work:

```
my_bundle:
    contents:
        - x.js
        - y.js

main_bundle:
    contents:
        - my_bundle
        - z.js
```

In the same way that:

```
my_bundle = Bundle('x.js', 'y.js')
main_bundle = Bundle(my_bundle,
    'z.js')
```

would work. Means I don't need to repeat my bundle includes if I'm using an inner bundle in more than one other outer bundle.
