### ISSUE TITLE
How to make less and compass work together?

### ISSUE THREAD

**Issue by wyuenho** [miracle2k/webassets#215]
Suppose I need to run the less filter on the bootstrap bundle first to generate a scss file, and then run compass on another scss file that imports the generated bootstrap scss file, how do I defined this order in a YAML config file? This is what I have now:

```yaml
bootstrap_scss:
  filters: less
  output: scss/_bootstrap.scss
  contents:
    - less/bootstrap/bootstrap.less
screen_scss:
  filters: compass
  output: css/screen.min.css
  contents:
    - bootstrap_scss
    # this file @imports the supposedly previously generated _bootstrap.scss
    - scss/screen.scss
```

When I run a build I get this error instead:

`Building bundle: css/admin/screen.min.css
Failed, error was: compass: subprocess had error: stderr=, stdout=    error bootstrap.less (Line 12: Invalid @import: expected end of line, was ";".)
, returncode=1`

It looks like the screen_scss is trying to run the less files from the referenced bundle through compass. I thought any referenced bundle outputs are to be generated first before running the referencing bundles. Please let me know if I've done anything wrong.
