### ISSUE TITLE
filter cssrewrite has no effect when put after scss filter with `as_output=True`

### ISSUE THREAD

**Issue by aconrad** [miracle2k/webassets#392]
It seems that the cssrewrite filter doesn't work when put after the scss filter if as_output is set to True. I was able to reproduce with a minimal use-case:

```python
# foo.py
import webassets
from webassets.filter import get_filter

env = webassets.Environment(directory='.', url='/')

scss = get_filter(
    'scss',
    as_output=True,
    load_paths='.',
    style='compressed',
)

cssrewrite = get_filter('cssrewrite', replace={'static/': 'assets/'})

bundle = webassets.Bundle(
    'file1.scss', 'file2.scss',
    filters=(scss, cssrewrite),
    output='packed.css'
)
env.register('my_bundle', bundle)
bundle.build()
```

```scss
// file1.scss
@import "foo";
```

```scss
// foo.scss
body {
  background-image: url("static/paper.gif")
}
```

```scss
// file2.scss
a {
  color: red;
}
```

Here is what happens when `as_output=True`:

```css
body{background-image:url("static/paper.gif")}a{color:red}
```

As you can see the URL is not rewritten to `assets/paper.gif`.

But with `as_output=False`:

```css
body{background-image:url("assets/paper.gif")}

a{color:red}
```

The URL is correctly rewritten but the output is not a one-liner and it's also much slower to compile (not obvious on this small test case but it is on bigger projects).

Am I misunderstanding how this is supposed to work or is it a bug?
